RPC:
  Config:
    SerializableType: JSON
    HeartCheckTime: 60 #每过60秒检查一次
    ExpireTime: 90 #过去多久算是过期
    HeartGap: 30 #发送心跳的间隔
  Provider:
    port: 8080
    ServiceName: nihao
  Server:
    Host: 127.0.0.1
    port: 80
  Register:
    port: 80



